dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    packages: libnss3-tools

language: node_js
node_js:
  - "6"
  - "8"
cache:
  npm: true
  directories:
    - $HOME/.npm
    - ./node_modules

before_install:
- npm config set prefer-offline true

before_script:
- export LIGHTHOUSE_CHROMIUM_PATH=`which google-chrome-stable`
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- if [ "$TRAVIS_BRANCH" = "master" ]; then export WITH_INSTALL=true; fi
- export WITH_INSTALL=true;

script:
- npm run lint
- npm run test
