dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    packages: libnss3-tools

language: node_js
node_js:
  - 6
  - 8

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

before_script:
- export LIGHTHOUSE_CHROMIUM_PATH=`which google-chrome-stable`
# - if [ "$TRAVIS_BRANCH" = "master" ]; then export SKIP_INSTALL=true; export WITH_LOG=true; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then export WITH_LOG=true; fi

script:
- npm run lint
- npm run test -- --verbose
