dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    packages: libnss3

language: node_js
node_js:
  - lts/*
  - node

git:
  depth: 1

branches:
  only:
    - master
    - next

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

# allow headful tests
before_install:
  # Enable user namespace cloning
  - 'sysctl kernel.unprivileged_userns_clone=1'
  # Launch XVFB
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - export WITH_LOG=true
  - export LIGHTHOUSE_CHROMIUM_PATH=`which google-chrome-stable`

script:
  - yarn test
